sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "skyhs3507@likelion.org"
  - git config --global user.name "seanlion"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "jU4NAW9QTZ7rIpZHMNKcHOAmqmbQUjMsjmZrxtf6YPSVoOQTpnYP5ZI/yOWnmyw/wdGuNAV3P3GMHzB2cz2wIhjGi/4+4E51n/gf6nnb5i9JoMbBezY7M8q97A5G3KDkh0GCTOHYPceo961cyvwJGZwVhYDaBhGytvQ6rUo0IQcmNdgGXaWtNdCnjzcIexkgTM3KEB99l8lPjoYFCkG8XX6Hq9x7SBRcvB4ESAFbGkmIUmZhxr3ErfuD879SkSNxfY9/qgEtPJ5rlnCMFh71+neQlo6UIHGi4pK1aAK0hZZPfjph5ICJffy2AZtOhfKilbAAZdc4mo9V58XdqRwDYXNZ5ikgFJaXB99pzCGuKmS0+5PNGlg7OXGGM5aIsoF0oXRQVlvM23mLBn5g369lhErpDIshQrIvsUNpK4rM3iGqzKA0dSsINIZCg5+UQLv0RhUOi/RJwAfrzX2hYaW1SG4o6UOPSre+hbRyaySXEQwJBGzImi1mvltRIPn2IZrCBdKGoKWso2sdRcrlZHuo3ELquUfQESijRI+cWrqkjetEUH8yqfTqscPojSlj0RmBwPed9wdgS5vDWNMuFt4JFui9aRvs5yXw+8QMfobKRLjmZrwiENd4/2Fv0APbT323rfhmctQDWirluLU/kV2PAeUFbx/48Vp2cdBETZKLFR8="
branches:
  only:
    - master