# for Travis CI. ##################
# Site settings
title:       Seung Huh's Page
email:       skyhs3507@gmail.com
author:      
description: "프로그래밍,테크,투자에 대해 이야기 하는 평범한 블로그입니다."
baseurl:     
date_format: "%b %-d, %Y"
header_pages:
 - home.html
 - about.html
 - categories.html
 - index.html
 - labs.html
size: 1
 

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-105982808-1
google_tag_manager:


# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
# Preview image for social media aka og:image and twitter:image
post_preview_image: true

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: seanlion-github-io


# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: seanlion
linkedin_username: seunghuh
medium_id:
paypal_url:

  # Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_linkedin: true

text:
  # pagination:
  #   newer:
  #   older:
  share_buttons:
    text:         '포스트 공유'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    linkedin:     'Share on LinkedIn'
    
  post:
    updated:        'Updated'
    # minute_read:    'minute read'
    related_posts:  '관련 포스트'
  index:
    coming_soon: 'Coming soon...'
  contact:
    # email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'ko_KR'

# 글 내 네비게이션
# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
# paginate_path:
# permalink:    pretty
permalink: /:year/:month/:title.html
# paginate:
sass:
  style: compressed
  
plugins:
  # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-paginate-v2
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 7

  # paginate_path : '/blogs/page:num/'
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: "/page:num/" # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale:

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################

destination: ./buildforlocal

production_url: https://seanlion.github.io/
source_url: https://github.com/seanlion/seanlionblog-repo

safe: False
lsi: False

username: seanlion
repo: seanlionblog-repo
branch: master